Repository zubzet/framework, pull requests merged in 2024-10, with the labels that each got.

#4 Fix phpdoc type errors and review existing explanations of parameters
  default/models/z_generalModel.php
  default/models/z_loginModel.php
  default/models/z_statisticsModel.php
  default/models/z_userModel.php
  main.php
  z_controller.php
  z_db.php
  z_model.php
  z_request.php
  z_requestResponseHandler.php
  z_response.php
  z_user.php
Labels: documentation

#3 WIP: restructure documentation for better ux
  docs/core-features/configuration.md
  docs/core-features/controllers-and-actions.md
  docs/core-features/layouts.md
  docs/core-features/models.md
  docs/core-features/mvc.md
  docs/core-features/permission-system.md
  docs/core-features/views.md
  docs/forms/auto-form-validation.md
  docs/frontend-integration/backend-requests.md
  docs/index.md
  docs/stylesheets/extra.css
  docs/z-admin/usage.md
  mkdocs.yml
Labels: documentation

#11 Remove old installer, updater and instance settings
  cv.txt
  default/controllers/ZController.php
  default/views/layout/z_admin_layout.php
  default/views/z_instance.php
  default/views/z_update.php
  docs/setup/how-to-update.md
  docs/z-admin/usage.md
  install.sql
  install/.htaccess
  install/index.php
  installer.php
  updater.php
Labels: refactor

#12 Log back in as executing user after impersonated logout
  z_response.php
Labels: enhancement

#10 Pass fixed values to update database when using form validation
  z_response.php
Labels: bug
